name: Pull Request Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.13.0'

      - name: Install uv
        uses: astral-sh/setup-uv@v5.3.0

      - name: Check formatting with Ruff
        run: |
          uv run ruff format --check .
          uv run ruff check . 